-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.administrator
(
    id serial NOT NULL,
    login character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default",
    role_id integer NOT NULL,
    station_id integer,
    name character varying(255) COLLATE pg_catalog."default",
    surname character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT administrator_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.calendar
(
    monday boolean,
    tuesday boolean,
    wednesday boolean,
    thursday boolean,
    friday boolean,
    saturday boolean,
    sunday boolean,
    start_date date,
    end_date date,
    service_id bigint NOT NULL DEFAULT nextval('calendar_key_column_seq'::regclass),
    CONSTRAINT calendar_pkey PRIMARY KEY (service_id)
);

CREATE TABLE IF NOT EXISTS public.carrier
(
    id serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default",
    code character varying(50) COLLATE pg_catalog."default",
    url character varying COLLATE pg_catalog."default",
    timezone character varying COLLATE pg_catalog."default",
    CONSTRAINT carrier_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.display
(
    id serial NOT NULL,
    type_id integer NOT NULL,
    station_id integer NOT NULL,
    platform_id integer,
    track_id integer,
    theme boolean,
    font character varying COLLATE pg_catalog."default",
    intermediates_number integer,
    main_color character varying COLLATE pg_catalog."default",
    background_color character varying COLLATE pg_catalog."default",
    alias character varying COLLATE pg_catalog."default",
    CONSTRAINT display_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.display_type
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default",
    picture_path character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT display_type_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.platform
(
    id serial NOT NULL,
    station_id integer NOT NULL,
    "number" character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT platform_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.role
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT role_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.route
(
    id character varying COLLATE pg_catalog."default" NOT NULL DEFAULT nextval('route_id_seq'::regclass),
    train_number character varying(50) COLLATE pg_catalog."default" NOT NULL,
    carrier_id integer NOT NULL,
    type_id integer NOT NULL,
    final_station_id integer,
    days_mask integer,
    valid_from date,
    valid_to date,
    CONSTRAINT route_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.route_type
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default",
    code character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT route_type_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.station
(
    id serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default",
    voice_model_id character varying COLLATE pg_catalog."default",
    voice_stability integer,
    voice_similarity integer,
    voice_style integer,
    CONSTRAINT station_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.stop
(
    id serial NOT NULL,
    arrival time without time zone,
    departure time without time zone,
    sequence integer,
    original_track_id integer NOT NULL,
    trip_id character varying COLLATE pg_catalog."default",
    CONSTRAINT stop_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.stop_status
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    date date NOT NULL,
    stop_id integer NOT NULL,
    arrival_delay integer,
    departure_delay integer,
    track_id integer,
    is_cancelled boolean,
    bus boolean,
    CONSTRAINT stop_status_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.track
(
    id serial NOT NULL,
    platform_id integer NOT NULL,
    "number" integer,
    CONSTRAINT track_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.trip
(
    route_id character varying COLLATE pg_catalog."default" NOT NULL,
    service_id integer NOT NULL,
    trip_id character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT trip_pkey PRIMARY KEY (trip_id)
);

CREATE TABLE IF NOT EXISTS public.voice_model
(
    id character varying COLLATE pg_catalog."default" NOT NULL,
    name character varying COLLATE pg_catalog."default",
    CONSTRAINT voice_model_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.administrator
    ADD CONSTRAINT administrator_role_fk FOREIGN KEY (role_id)
    REFERENCES public.role (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.administrator
    ADD CONSTRAINT administrator_station_fk FOREIGN KEY (station_id)
    REFERENCES public.station (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.display
    ADD CONSTRAINT display_platform_fk FOREIGN KEY (platform_id)
    REFERENCES public.platform (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.display
    ADD CONSTRAINT display_station_fk FOREIGN KEY (station_id)
    REFERENCES public.station (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.display
    ADD CONSTRAINT display_track_fk FOREIGN KEY (track_id)
    REFERENCES public.track (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.display
    ADD CONSTRAINT display_type_fk FOREIGN KEY (type_id)
    REFERENCES public.display_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.platform
    ADD CONSTRAINT platform_station_fk FOREIGN KEY (station_id)
    REFERENCES public.station (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.route
    ADD CONSTRAINT route_carrier_fk FOREIGN KEY (carrier_id)
    REFERENCES public.carrier (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.route
    ADD CONSTRAINT route_station_fk FOREIGN KEY (final_station_id)
    REFERENCES public.station (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.route
    ADD CONSTRAINT route_type_fk FOREIGN KEY (type_id)
    REFERENCES public.route_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.station
    ADD CONSTRAINT station_voice_model_fk FOREIGN KEY (voice_model_id)
    REFERENCES public.voice_model (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.stop
    ADD CONSTRAINT stop_original_track_fk FOREIGN KEY (original_track_id)
    REFERENCES public.track (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.stop
    ADD CONSTRAINT stop_trip_fd FOREIGN KEY (trip_id)
    REFERENCES public.trip (trip_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.stop_status
    ADD CONSTRAINT stop_status_stop_fk FOREIGN KEY (stop_id)
    REFERENCES public.stop (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.stop_status
    ADD CONSTRAINT stop_status_track_fk FOREIGN KEY (track_id)
    REFERENCES public.track (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.track
    ADD CONSTRAINT track_platform_fk FOREIGN KEY (platform_id)
    REFERENCES public.platform (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.trip
    ADD CONSTRAINT trip_route_id_fkey FOREIGN KEY (route_id)
    REFERENCES public.route (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.trip
    ADD CONSTRAINT trip_service_id_fkey FOREIGN KEY (service_id)
    REFERENCES public.calendar (service_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;